"""empty message

Revision ID: 15f74d07f5db
Revises: 25acbb7ff00d
Create Date: 2014-04-01 14:32:34.968000

"""

# revision identifiers, used by Alembic.
revision = '15f74d07f5db'
down_revision = '25acbb7ff00d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
