"""empty message

Revision ID: 273798e8d52c
Revises: 4c1e873830
Create Date: 2014-04-03 12:27:34.330000

"""

# revision identifiers, used by Alembic.
revision = '273798e8d52c'
down_revision = '4c1e873830'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_actions', sa.Column('recharge', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_actions', 'recharge')
    ### end Alembic commands ###
