"""empty message

Revision ID: 2aee1a540541
Revises: 6c8e5c55507
Create Date: 2014-04-16 11:59:00.005000

"""

# revision identifiers, used by Alembic.
revision = '2aee1a540541'
down_revision = '6c8e5c55507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
