"""empty message

Revision ID: 344c64ddeb7f
Revises: 45124ff3e591
Create Date: 2014-04-04 19:56:55.868000

"""

# revision identifiers, used by Alembic.
revision = '344c64ddeb7f'
down_revision = '45124ff3e591'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_actions', sa.Column('aura_range', sa.String(length=64), nullable=True))
    op.add_column('monster_actions', sa.Column('trigger_usage', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_actions', 'trigger_usage')
    op.drop_column('monster_actions', 'aura_range')
    ### end Alembic commands ###
