"""empty message



Revision ID: 3bbc132ed948

Revises: de610f30533

Create Date: 2014-05-07 12:06:19.633000



"""



# revision identifiers, used by Alembic.

revision = '3bbc132ed948'

down_revision = 'de610f30533'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('hash_key', sa.String(length=5), nullable=True))
    op.create_index('ix_encounters_hash_key', 'encounters', ['hash_key'], unique=False)
    op.drop_index('ix_monster_actions_hash_key', table_name='monster_actions')
    op.drop_column('monster_actions', 'hash_key')
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_monster_actions_hash_key', 'monster_actions', ['hash_key'], unique=False)
    op.add_column('monster_actions', sa.Column('hash_key', sa.VARCHAR(length=5), nullable=True))
    op.drop_index('ix_encounters_hash_key', table_name='encounters')
    op.drop_column('encounters', 'hash_key')
    ### end Alembic commands ###

