"""empty message

Revision ID: 3df8c312c845
Revises: 1547d15c7092
Create Date: 2014-05-06 12:05:39.038000

"""

# revision identifiers, used by Alembic.
revision = '3df8c312c845'
down_revision = '1547d15c7092'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('aura_range', sa.String(length=64), nullable=True),
    sa.Column('recharge', sa.String(length=64), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('trigger', sa.String(length=512), nullable=True),
    sa.Column('trigger_usage', sa.String(length=512), nullable=True),
    sa.Column('attack', sa.String(length=64), nullable=True),
    sa.Column('hit', sa.String(length=512), nullable=True),
    sa.Column('miss', sa.String(length=512), nullable=True),
    sa.Column('effect', sa.String(length=512), nullable=True),
    sa.Column('secondary_attack', sa.String(length=512), nullable=True),
    sa.Column('aftereffect', sa.String(length=512), nullable=True),
    sa.Column('special', sa.String(length=512), nullable=True),
    sa.Column('keywords', sa.String(length=64), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Xmonster_actions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Xmonster_actions',
    sa.Column('id', sa.INTEGER(), server_default='nextval(\'"Xmonster_actions_id_seq"\'::regclass)', nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('aura_range', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('recharge', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('trigger_usage', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('attack', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('hit', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('miss', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('secondary_attack', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('aftereffect', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('special', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('monster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], [u'monsters.id'], name=u'Xmonster_actions_monster_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'Xmonster_actions_pkey')
    )
    op.drop_table('monster_actions')
    ### end Alembic commands ###
