"""empty message

Revision ID: 41eb196515df
Revises: 344c64ddeb7f
Create Date: 2014-04-05 10:26:52.435772

"""

# revision identifiers, used by Alembic.
revision = '41eb196515df'
down_revision = '344c64ddeb7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_actions', 'usage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_actions', sa.Column('usage', sa.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
