"""empty message

Revision ID: 4216530af38f
Revises: 2aee1a540541
Create Date: 2014-04-16 12:00:38.950000

"""

# revision identifiers, used by Alembic.
revision = '4216530af38f'
down_revision = '2aee1a540541'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
