"""empty message

Revision ID: 45124ff3e591
Revises: 554854085837
Create Date: 2014-04-03 13:51:00.942000

"""

# revision identifiers, used by Alembic.
revision = '45124ff3e591'
down_revision = '554854085837'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('usage', sa.String(length=64), nullable=True),
    sa.Column('recharge', sa.String(length=64), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('trigger', sa.String(length=256), nullable=True),
    sa.Column('attack', sa.String(length=64), nullable=True),
    sa.Column('hit', sa.String(length=256), nullable=True),
    sa.Column('miss', sa.String(length=256), nullable=True),
    sa.Column('effect', sa.String(length=256), nullable=True),
    sa.Column('secondary_attack', sa.String(length=256), nullable=True),
    sa.Column('aftereffect', sa.String(length=256), nullable=True),
    sa.Column('special', sa.String(length=512), nullable=True),
    sa.Column('keywords', sa.String(length=64), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('xmonster_actions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xmonster_actions',
    sa.Column('id', sa.INTEGER(), server_default="nextval('xmonster_actions_id_seq'::regclass)", nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('usage', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('recharge', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('attack', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('hit', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('miss', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('secondary_attack', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('aftereffect', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('special', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('monster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], [u'monsters.id'], name=u'xmonster_actions_monster_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'xmonster_actions_pkey')
    )
    op.drop_table('monster_actions')
    ### end Alembic commands ###
