"""empty message

Revision ID: 4bfbaa75f291
Revises: 2f902d55319e
Create Date: 2014-04-03 10:49:28.777000

"""

# revision identifiers, used by Alembic.
revision = '4bfbaa75f291'
down_revision = '2f902d55319e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
