"""empty message

Revision ID: 4c1e873830
Revises: 4bfbaa75f291
Create Date: 2014-04-03 12:25:58.207000

"""

# revision identifiers, used by Alembic.
revision = '4c1e873830'
down_revision = '4bfbaa75f291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster_actions', 'recharge')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_actions', sa.Column('recharge', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
