"""empty message

Revision ID: 4d23f9fa5595
Revises: 273798e8d52c
Create Date: 2014-04-03 13:49:31.172000

"""

# revision identifiers, used by Alembic.
revision = '4d23f9fa5595'
down_revision = '273798e8d52c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
