"""empty message

Revision ID: 509e6108821a
Revises: 984b76f610f
Create Date: 2014-04-14 16:26:26.284000

"""

# revision identifiers, used by Alembic.
revision = '509e6108821a'
down_revision = '984b76f610f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter_entry_statuses', sa.Column('encounter_entry_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter_entry_statuses', 'encounter_entry_id')
    ### end Alembic commands ###
