"""empty message

Revision ID: 53e1c070900e
Revises: 5ad47c75fbb5
Create Date: 2014-05-06 11:48:31.574000

"""

# revision identifiers, used by Alembic.
revision = '53e1c070900e'
down_revision = '5ad47c75fbb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
