"""empty message

Revision ID: 6c8e5c55507
Revises: 509e6108821a
Create Date: 2014-04-15 16:40:23.916000

"""

# revision identifiers, used by Alembic.
revision = '6c8e5c55507'
down_revision = '509e6108821a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('round', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'round')
    ### end Alembic commands ###
