"""empty message

Revision ID: 8caeebb643a
Revises: 4216530af38f
Create Date: 2014-04-16 12:02:11.318000

"""

# revision identifiers, used by Alembic.
revision = '8caeebb643a'
down_revision = '4216530af38f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
