"""empty message

Revision ID: 984b76f610f
Revises: 4bf70bd6351c
Create Date: 2014-04-14 15:15:43.566000

"""

# revision identifiers, used by Alembic.
revision = '984b76f610f'
down_revision = '4bf70bd6351c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_entry_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('initiative_order', sa.Integer(), nullable=True),
    sa.Column('spawn_index', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('temp_hp', sa.Integer(), nullable=True),
    sa.Column('visible', sa.SmallInteger(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounter_entries')
    op.drop_table('encounter_entry_statuses')
    ### end Alembic commands ###
