"""empty message

Revision ID: d7ff304d9ea
Revises: 53e1c070900e
Create Date: 2014-05-06 11:58:36.361000

"""

# revision identifiers, used by Alembic.
revision = 'd7ff304d9ea'
down_revision = '53e1c070900e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
