"""empty message

Revision ID: dc1a7ceb7cf
Revises: 4117ef92c030
Create Date: 2014-04-09 10:37:23.502000

"""

# revision identifiers, used by Alembic.
revision = 'dc1a7ceb7cf'
down_revision = '4117ef92c030'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('spawn_count', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    ### end Alembic commands ###
